### ISSUE TITLE
Круглосуточный календарь; Endless calendar

### ISSUE THREAD

**Issue by NickShtefan** [Gravideots/GameCalendarKit#1]
Нужна реализация бесконечного календаря
В текущий момент имеется время начала и окончания рабочего дня.  По окончанию рабочего дня, время перескакивает на начало нового дня(получаем событие окончания рабочего дня), после чего необходимо вызвать начало нового дня, для продолжения работы календаря. 

Необходимо реализовать безостановочную работу календаря. 
Дополнительные события: 
 Midnight event - возникает в 00:00

**Comment by Gravideots** [comment]
Need to implement an endless calendar
Currently there is a start and end time of the working day. At the end of the working day, the time jumps to the beginning of a new day (we receive the endDay event), after which it is necessary to call the beginning of a new day, to continue the work of the calendar.

It is necessary to implement the non-stop work of the calendar.
Additional events:
Midnight event - occurs at 00:00
