### ISSUE TITLE
Повторяющиеся события; Recurring events

### ISSUE THREAD

**Issue by NickShtefan** [Gravideots/GameCalendarKit#7]
Возможность отметить событие на весь день (с 00.00 до 23:59)
Возможность выбрать повтор события
 Каждый день
 Каждую неделю 
 Каждый месяц 
 Каждый год
Возможность указывать количество повторений события

**Comment by Gravideots** [comment]
Event for the whole day (from 00.00 to 23:59)
Option to select an event repeat
everyday
Every week
Every month
Every year
Ability to specify the number of times an event is repeated
